### Register

POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json


{
    "username": "sdsdsd",
    "email": "sdsdsds@test.com",
    "password": "1234"
}

### Login

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "samu@test.com",
    "password": "1234"
}

### Update User

PUT http://localhost:5000/api/user/626948426a669628de657621 HTTP/1.1
content-type: application/json

{
    "username": "newusername",
    "userID": "626948426a669628de657621"
}

### Delete User

DELETE http://localhost:5000/api/user/626948426a669628de657621 HTTP/1.1
content-type: application/json

{
    "userID": "626948426a669628de657621"
}

### Get User

GET http://localhost:5000/api/user/626a5da704fbbc32e29b6259 HTTP/1.1
content-type: application/json

### Add friend to user

PUT http://localhost:5000/api/user/626a5d8004fbbc32e29b6257/friend HTTP/1.1
content-type: application/json

{
    "userID": "626a5da704fbbc32e29b6259"
}

### Remove friend from user

PUT http://localhost:5000/api/user/626a5d8004fbbc32e29b6257/unfriend HTTP/1.1
content-type: application/json

{
    "userID": "626a5da704fbbc32e29b6259"
}