### Create Group

POST http://localhost:8000/api/auth/create-group HTTP/1.1
content-type: application/json

{
    "userID": "62c468d6b532628ed78a3e4c",
    "name": "Test group 01"
    
}

### Get Group

GET http://localhost:8000/api/group/62c469d05a3f8f5396f47a73 HTTP/1.1
content-type: application/json


### Join Group

POST http://localhost:8000/api/group/join-group HTTP/1.1
content-type: application/json

{
    "userID": "62c479123f2593b7997c2dc7",
    "groupID": "62c469d05a3f8f5396f47a73"
    
}

### Add Entry
POST http://localhost:8000/api/entry/add HTTP/1.1
content-type: application/json

{
    "name": "Food and Drinks",
    "amount": 500,
    "payerID": "62c468d6b532628ed78a3e4c",
    "paidForID": ["62c479123f2593b7997c2dc7"],
    "groupID": "62c469d05a3f8f5396f47a73"
}