### Register

POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json


{
    "name": "shubham",
    "email": "test02@gmail.com",
    "password": "12345"
}

# {
#     "name": "sahilsahil",
#     "email": "test01@gmail.com",
#     "password": "12345"
# }

### Login

POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test02@gmail.com",
    "password": "12345"
}

### Update User

PUT http://localhost:8000/api/user/62c40b9e9107606727e01f0f HTTP/1.1
content-type: application/json

{
    "name": "sahil new name",
    "userID": "62c40b9e9107606727e01f0f"
}

### Delete User

DELETE http://localhost:8000/api/user/62c40b9e9107606727e01f0f HTTP/1.1
content-type: application/json

{
    "userID": "62c40b9e9107606727e01f0f"
}

### Get User

GET http://localhost:8000/api/user/62c468d6b532628ed78a3e4c HTTP/1.1
content-type: application/json

